#!/usr/bin/env python
import os

Import('env')

def dist(filename=''):
	return os.path.join(os.environ.get('DISTDIR', 'dist'), filename)

unshare = env.Program(target='unshare-pid', source=['unshare-pid.c'])

env.Install(dist('lib/python'), ['net_sandbox.py'])
env.Install(dist('bin'), [unshare])
